project:
  type: website

website:
  title: "Kyle Bradbury's Blog"
  navbar:
    right:
      - text: About
        href: about.qmd
        # icon: file-person
      - text: Homepage
        # icon: house-fill
        href: https://kylebradbury.org/
      # - text: LinkedIn
        # icon: linkedin
        # href: https://www.linkedin.com/in/bradburykyle/
        
      # - icon: mortarboard-fill
      #   href: https://scholar.google.com/citations?user=eBm0d6kAAAAJ&hl=en
  page-footer:
    center: 
      - text: "Copyright © Kyle Bradbury 2023"
  favicon: favicon.ico
format:
  html:
    theme: cosmo
    css: styles.css



